apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-cloudpublisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ua-cloudpublisher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ua-cloudpublisher
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: ua-cloudpublisher
        image: ghcr.io/barnstee/ua-cloudpublisher:main
        imagePullPolicy: IfNotPresent
        env:
        - name: USE_KAFKA
          value: "1"
        - name: STORAGE_TYPE
          value: "Azure"
        - name: STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=[yourstorageaccountname];AccountKey=[key];EndpointSuffix=core.windows.net"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: ua-cloudpublisher
  labels:
    name: ua-cloudpublisher
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ua-cloudpublisher